version: "3.1"

services:
  device-scraper:
    container_name: device-scraper
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: device-scraper:latest
    networks:
      - proxynet
networks:
  proxynet:
    name: kavanest-network
