version: "3.1"

services:
  mongo:
    container_name: graphql-mongo
    image: mongo
    networks:
      - proxynet
    # volumes:
    # - ./data:/data/db
    ports:
      - "27017:27017"

  device-scraper:
    container_name: device-scraper
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: device-scraper:latest
    networks:
      - proxynet
    environment:
      - URI=mongodb://mongo:27017/devices
      - MQTT=mqtt://kavanet.io

networks:
  proxynet:
    name: kavanest-network
