version: "3.1"

services:
  kavanest-scraper:
    container_name: kavanest-scraper
    image: kavanest-scraper
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    environment:
      - MQTT=mqtt://192.168.1.66
      - MONGO=mongodb://kavanest-local-mongo:27017

networks:
  proxynet:
    name: kavanest-devnet
