version: "3.1"

services:
  kavanest-scraper:
    container_name: kavanest-scraper
    image: kavanest-scraper
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    expose:
      - 3100
    ports:
      - 3100:3100
    environment:
      - MQTT=mqtt://mosquitto
      - MONGO=mongodb://kavanest-mongo:27017

networks:
  proxynet:
    name: kavanest-devnet
    external: true
