version: "3.1"

services:
  kavanest-scraper:
    container_name: kavanest-scraper
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    environment:
      - URI=mongodb://kavanest-mongo:27017/devices
      - MQTT=mqtt://kavanet.io

networks:
  proxynet:
    name: kavanest-devnet
