name: kavanest-scraper

namespace: kavanest
env:
  APP_VERSION: f8f1c3a6df2f4b28606c879c06a431565f46eef9

deployment:
  - name: kavanest-scraper
    image: invisibug/kavanest-scraper
    ports:
    - port: 27017
    env:
    - name: MONGO
      value: mongodb://kavanest-mongo

    - name: MQTT
      value: mqtt:mqtt.kavanet.io

service:
  clusterIP:
    - name: kavanest-scraper
      selector: kavanest-scraper
      ports:
        - port: 3100

ingress:
  - name: socket.kavanet.io
    selector: kavanest-scraper
    path: /
    port: 3100
    host: socket.kavanet.io
