name: kavanest-scraper

namespace: kavanest
env:
  APP_VERSION: 689c3370b463d60c5da9c69c67ba20efc1cb6e81

deployment:
  - name: kavanest-scraper
    image: invisibug/kavanest-scraper
    ports:
    - port: 27017
    env:
    - name: MONGO
      value: mongodb://kavanest-mongo

    - name: MQTT
      value: mqtt:mqtt.kavanet.io

service:
  clusterIP:
    - name: kavanest-scraper
      selector: kavanest-scraper
      ports:
        - port: 3100

ingress:
  - name: socket.kavanet.io
    selector: kavanest-scraper
    path: /
    port: 3100
    host: socket.kavanet.io
