name: kavanest-test-scraper

namespace: kavanest-test

deployment:
  - name: kavanest-scraper
    image: 192.168.1.61:5000/kavanest-scraper
    ports:
    - port: 27017
    env:
    - name: ENVIRONMENT
      value: test

    - name: MONGO_TEST
      value: mongodb://kavanest-test-mongo:27017

    - name: MQTT_TEST
      value: mqtt://kavanest-simulator
