name: kavanest-test-scraper

namespace: kavanest-test
env:
  APP_VERSION: 963f167f8bea8a9f6cc4554dbdc1c71f16ddd3b5

deployment:
  - name: kavanest-test-scraper
    image: invisibug/kavanest-test-scraper
    ports:
    - port: 27017
    env:
    - name: MONGO
      value: mongodb://kavanest-test-mongo

    - name: MQTT
      value: mqtt://kavanest-test-mqtt

service:
  clusterIP:
    - name: kavanest-test-scraper
      selector: kavanest-test-scraper
      ports:
        - port: 3100

ingress:
  - name: test.socket.kavanet.io
    selector: kavanest-test-scraper
    path: /
    port: 3100
    host: test.socket.kavanet.io
